# Generated by Django 3.0.7 on 2020-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
