# Generated by Django 3.0.7 on 2020-08-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200820_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='', upload_to='blog_photo', verbose_name='Foto de encabezado'),
        ),
    ]
