# Generated by Django 3.0.7 on 2020-08-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publicated',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
