# Generated by Django 3.0.7 on 2020-08-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_publicated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publicated',
            new_name='published',
        ),
    ]
