# Generated by Django 3.0.8 on 2020-12-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201112_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
