# Generated by Django 3.0.8 on 2020-12-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201209_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
