# Generated by Django 3.0.8 on 2020-12-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201223_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photo', verbose_name='Foto 1 (opcional)'),
        ),
        migrations.AddField(
            model_name='blog',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photo', verbose_name='Foto 2 (opcional)'),
        ),
    ]
