# Generated by Django 3.0.8 on 2020-08-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='tamaño',
            field=models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Chico', 'Chico')], default='Grande', max_length=40, verbose_name='Tamaño'),
            preserve_default=False,
        ),
    ]
