# Generated by Django 3.0.8 on 2020-08-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animal_tamaño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='carácter',
            new_name='caracter',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='desparasitados',
            new_name='desparasitado',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='castracion',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='rabia',
        ),
        migrations.AddField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=True, verbose_name='Castrado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='vacunado',
            field=models.BooleanField(default=True, verbose_name='Vacunado'),
            preserve_default=False,
        ),
    ]
