# Generated by Django 3.0.8 on 2020-08-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200810_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
