# Generated by Django 3.0.8 on 2020-11-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_delete_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('contact_category', models.CharField(choices=[('CONSULTA', 'Consulta'), ('SUGERENCIA', 'Sugerencia'), ('URGENTE', 'Urgente'), ('DONACIONES', 'Donaciones'), ('OFERTA', 'Oferta'), ('OTRO', 'Otro')], default='CONSULTA', max_length=10)),
                ('subject', models.CharField(max_length=80)),
                ('body', models.CharField(max_length=2000)),
                ('answered', models.BooleanField()),
            ],
        ),
    ]
