# Generated by Django 3.0.8 on 2020-11-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_category',
            field=models.CharField(max_length=10),
        ),
    ]
