# Generated by Django 3.0.8 on 2020-11-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201110_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_category',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('SUGERENCIA', 'Sugerencia'), ('URGENTE', 'Urgente'), ('DONACIONES', 'Donaciones'), ('OFERTA', 'Oferta'), ('OTRO', 'Otro')], default='CONSULTA', max_length=10),
        ),
    ]
