# Generated by Django 3.0.8 on 2020-11-16 18:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201116_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginadonaciones',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='paginainicio',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Texto'),
        ),
    ]
