# Generated by Django 3.0.8 on 2020-11-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201117_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=80, verbose_name='Asunto'),
        ),
    ]
