# Generated by Django 3.0.8 on 2020-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201117_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.CharField(max_length=2000, verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Apellido'),
        ),
    ]
