# Generated by Django 3.0.8 on 2020-12-11 02:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201117_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginadonaciones',
            name='description',
        ),
        migrations.AddField(
            model_name='paginadonaciones',
            name='info_cbu',
            field=ckeditor.fields.RichTextField(default='Actualmente no disponible.', verbose_name='Info de CBU'),
        ),
    ]
