# Generated by Django 3.0.8 on 2020-11-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201117_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginadonaciones',
            name='description',
        ),
    ]
