# Generated by Django 3.0.8 on 2020-11-11 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tipo_animal', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=40, verbose_name='Tipo de animal')),
                ('raza', models.CharField(max_length=255, verbose_name='Raza')),
                ('tamaño', models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Chico', 'Chico')], max_length=40, verbose_name='Tamaño')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='foto1', verbose_name='Foto 1')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='foto2', verbose_name='Foto 2')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('Indefinido', 'Indefinido')], max_length=40, verbose_name='Sexo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('caracter', models.TextField(blank=True, null=True, verbose_name='Caracter')),
                ('vacunado', models.BooleanField(verbose_name='Vacunado')),
                ('desparasitado', models.BooleanField(verbose_name='Desparacitado')),
                ('castrado', models.BooleanField(verbose_name='Castrado')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
    ]
