# Generated by Django 3.0.8 on 2020-11-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='publicado',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
