# Generated by Django 3.0.8 on 2020-08-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AddField(
            model_name='animal',
            name='descripcion',
            field=models.TextField(default='ads', verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
