# Generated by Django 3.0.8 on 2020-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20200811_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='updated',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='created',
            new_name='creado',
        ),
        migrations.AddField(
            model_name='animal',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
