# Generated by Django 3.0.8 on 2020-12-02 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopcion', '0002_auto_20201201_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
    ]
