# Generated by Django 3.0.8 on 2020-11-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20201111_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='desparasitado',
            field=models.BooleanField(verbose_name='Desparasitado'),
        ),
    ]
