# Generated by Django 3.0.8 on 2020-08-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20200811_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='foto1', verbose_name='Foto 1'),
        ),
        migrations.AddField(
            model_name='animal',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='foto1', verbose_name='Foto 1'),
        ),
    ]
