# Generated by Django 3.0.8 on 2020-12-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20201201_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualización'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='caracter',
            field=models.TextField(blank=True, null=True, verbose_name='Carácter'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
