# Generated by Django 3.0.7 on 2020-08-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_auto_20200811_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='foto2', verbose_name='Foto 2'),
        ),
    ]
