# Generated by Django 3.0.8 on 2020-12-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_auto_20201201_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='tiempo',
            field=models.CharField(choices=[('Días', 'Dias'), ('Semanas', 'Semanas'), ('Meses', 'Meses'), ('Años', 'Año')], default='', max_length=50, verbose_name='Tiempo'),
        ),
    ]
