# Generated by Django 3.0.8 on 2020-12-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0007_auto_20201201_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tipo_animal',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=40, verbose_name='Tipo de animal'),
        ),
    ]
