# Generated by Django 3.0.8 on 2020-12-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0010_auto_20201202_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email de contacto'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raza',
            field=models.CharField(max_length=30, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('Indefinido', 'Indefinido')], max_length=20, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tamaño',
            field=models.CharField(choices=[('Chico', 'Chico'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=40, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tiempo',
            field=models.CharField(choices=[('Dias', 'Dias'), ('Semanas', 'Semanas'), ('Meses', 'Meses'), ('Años', 'Años')], max_length=20, verbose_name='Tiempo'),
        ),
    ]
