# Generated by Django 3.0.8 on 2020-11-19 19:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Efemerides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('texto', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('color', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('danger', 'Rojo'), ('warning', 'Amarillo'), ('info', 'Cian'), ('dark', 'Negro')], max_length=50, verbose_name='Color')),
                ('fecha_festividad', models.DateField(verbose_name='Día de festividad')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Efemérides',
                'verbose_name_plural': 'Efemérides',
            },
        ),
    ]
