# Generated by Django 3.0.8 on 2020-11-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efemerides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='efemerides',
            name='foto',
            field=models.ImageField(default='', upload_to='efemerides_photo', verbose_name='Foto de la Tematica'),
        ),
    ]
