# Generated by Django 3.0.8 on 2020-11-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efemerides', '0003_auto_20201121_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efemerides',
            name='fecha_festividad',
            field=models.DateField(unique=True, verbose_name='Día de festividad'),
        ),
    ]
