# Generated by Django 3.0.8 on 2020-12-27 03:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efemerides', '0004_auto_20201124_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efemerides',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
