# Generated by Django 3.0.8 on 2020-12-28 19:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efemerides', '0005_auto_20201227_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efemerides',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto (Opcional)'),
        ),
    ]
